#!/usr/bin/env node
// jura-contracts codegen orchestrator (Phase 3.1 of the engineering foundation plan).
//
// For every schemas/*.schema.json:
//   - generates a Zod schema into generated/typescript/src/<name>.ts (json-schema-to-zod)
//   - generates a Pydantic model into generated/python/juraai_contracts/<name>.py (datamodel-code-generator)
// Then writes an index for each language re-exporting every generated schema.
//
// Never hand-edit anything under generated/ - it is fully regenerated by this script.

import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const SCHEMAS_DIR = join(ROOT, "schemas");
const TS_OUT_DIR = join(ROOT, "generated", "typescript", "src");
const PY_OUT_DIR = join(ROOT, "generated", "python", "juraai_contracts");
// Invoke the CLI's JS entrypoint directly via `node`, bypassing npx/cmd.exe shell wrapping -
// on Windows, `shell: true` + a path containing spaces (this repo lives under "JURA PROJECT")
// gets mis-split by cmd.exe's own quoting rules even when node passes a clean argv array.
const JSON_SCHEMA_TO_ZOD_CLI = join(ROOT, "node_modules", "json-schema-to-zod", "dist", "cjs", "cli.js");

function pascalCase(name) {
  return name
    .split(/[-_]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function main() {
  mkdirSync(TS_OUT_DIR, { recursive: true });
  mkdirSync(PY_OUT_DIR, { recursive: true });

  // .sort() is required, not cosmetic: readdirSync's order is filesystem-dependent (this repo
  // hit real drift between a Windows dev machine and Linux CI - the two produced different
  // index.ts/__init__.py export orderings from the identical schema files, which then failed
  // CI's own "regenerate and diff" drift check). Sorting makes the output byte-for-byte
  // reproducible regardless of OS/filesystem.
  const schemaFiles = readdirSync(SCHEMAS_DIR)
    .filter((f) => f.endsWith(".schema.json"))
    .sort();
  if (schemaFiles.length === 0) {
    console.error("No schemas found under schemas/ - nothing to generate.");
    process.exit(1);
  }

  const tsExports = [];
  const pyExports = [];

  for (const file of schemaFiles) {
    const baseName = file.replace(/\.schema\.json$/, "").replace(/^_/, "");
    const schemaName = pascalCase(baseName);
    const schemaPath = join(SCHEMAS_DIR, file);

    // Pre-flight guard: json-schema-to-zod emits every "description" as a /** ... */ JSDoc
    // comment. A description string containing a literal "*/" prematurely closes that comment
    // and produces a syntactically broken .ts file - a real bug this script hit once already
    // (see good-law-status-MAPPING.md's own history). Fail loud, at the source schema, with a
    // clear message, rather than downstream as a cryptic SyntaxError in generated code.
    assertNoCommentTerminator(schemaPath);

    // --- TypeScript: json-schema-to-zod ---------------------------------------------------
    const tsOutPath = join(TS_OUT_DIR, `${baseName}.ts`);
    console.log(`[ts]  ${file} -> generated/typescript/src/${baseName}.ts`);
    execFileSync(
      process.execPath,
      [
        JSON_SCHEMA_TO_ZOD_CLI,
        "-i", schemaPath,
        "-o", tsOutPath,
        "-n", `${schemaName}Schema`,
        "-t", schemaName,
        "-m", "esm",
        "-wj",
      ],
      { stdio: "inherit", cwd: ROOT },
    );
    tsExports.push(baseName);

    // --- Python: datamodel-code-generator --------------------------------------------------
    const pyOutPath = join(PY_OUT_DIR, `${toSnakeCase(baseName)}.py`);
    console.log(`[py]  ${file} -> generated/python/juraai_contracts/${toSnakeCase(baseName)}.py`);
    execFileSync(
      "uv",
      [
        "run", "datamodel-codegen",
        "--input", schemaPath,
        "--input-file-type", "jsonschema",
        "--output", pyOutPath,
        "--output-model-type", "pydantic_v2.BaseModel",
        "--class-name", schemaName,
        "--use-schema-description",
        "--target-python-version", "3.12",
        "--disable-timestamp",
        // Emit typing.Annotated[str, StringConstraints(...)] instead of bare constr()/conint()
        // calls-as-annotations - mypy (without the pydantic mypy plugin, which this repo does
        // not enable) rejects a function call used directly as a type annotation ("Cannot use a
        // function call in a type annotation"), which the first 3 real (non-trivial) schemas hit
        // the moment they added a minLength/minimum constraint.
        "--use-annotated",
      ],
      { stdio: "inherit", cwd: ROOT },
    );
    pyExports.push(toSnakeCase(baseName));
  }

  // Index files are sorted ALPHABETICALLY BY MODULE NAME, deliberately independent of the
  // schemas/ processing order above - Python's import-sort convention (ruff's I001, which this
  // repo enforces) wants module-alphabetical order, not source-file order, and the two can
  // legitimately differ (e.g. "_trivial-ping" sorts before "citator-finding" as a filename, but
  // "trivial_ping" sorts after both "citator_finding" and "good_law_status" as a module name).
  const sortedTsExports = [...tsExports].sort();
  const sortedPyExports = [...pyExports].sort();

  // --- TS index ----------------------------------------------------------------------------
  const tsIndex =
    "// AUTO-GENERATED by codegen/generate.mjs - do not hand-edit.\n" +
    sortedTsExports.map((n) => `export * from "./${n}.js";`).join("\n") +
    "\n";
  writeFileSync(join(TS_OUT_DIR, "index.ts"), tsIndex);

  // --- Python index --------------------------------------------------------------------------
  // No `# noqa` comment: this repo's ruff config doesn't enable F401/F403 (see pyproject.toml),
  // so a noqa here is itself an unused-directive lint error (RUF100) - the exact bug that broke
  // the first CI run. If a consuming repo's ruff config DOES enable those rules, that repo's own
  // per-file-ignore belongs in ITS pyproject.toml, not baked into this generated file.
  const pyIndex =
    '"""AUTO-GENERATED by codegen/generate.mjs - do not hand-edit."""\n\n' +
    sortedPyExports.map((n) => `from .${n} import *`).join("\n") +
    "\n";
  writeFileSync(join(PY_OUT_DIR, "__init__.py"), pyIndex);

  // PEP 561 marker (found missing by a downstream consumer, 2026-07-27): without this, every
  // mypy run in every consuming repo treats this package as untyped (import-untyped), silently
  // losing type-checking on every CitatorFinding/GoodLawStatus/etc. usage - exactly the kind of
  // gap that's invisible until a real consumer actually runs mypy against it. Empty marker file,
  // not schema-derived, so it's written here rather than per-schema.
  writeFileSync(join(PY_OUT_DIR, "py.typed"), "");

  console.log(`\nGenerated ${schemaFiles.length} schema(s) -> TypeScript + Python. Done.`);
}

function toSnakeCase(name) {
  return name.replace(/-/g, "_");
}

function assertNoCommentTerminator(schemaPath) {
  const raw = readFileSync(schemaPath, "utf-8");
  const schema = JSON.parse(raw);
  const offenders = [];
  function walk(value, path) {
    if (typeof value === "string") {
      if (value.includes("*/")) offenders.push(path);
    } else if (Array.isArray(value)) {
      value.forEach((v, i) => walk(v, `${path}[${i}]`));
    } else if (value && typeof value === "object") {
      for (const [k, v] of Object.entries(value)) walk(v, path ? `${path}.${k}` : k);
    }
  }
  walk(schema, "");
  if (offenders.length > 0) {
    console.error(
      `\n${schemaPath} contains a literal "*/" in: ${offenders.join(", ")}.\n` +
        `This closes the generated JSDoc comment early and breaks the .ts file's syntax. ` +
        `Reword the text to avoid the exact "*/" sequence (e.g. "the TS and Python validators" ` +
        `instead of "validators/*/foo.*").`,
    );
    process.exit(1);
  }
}

main();
